https://jovian.ai/aakashns/python-numerical-computing-with-numpy

Given some climate data for a region, we can now predict the yield of apples. Here's some sample data:

<img src="https://i.imgur.com/TXPBiqv.png" style="width:360px;">

To begin, we can define some variables to record climate data for a region.

In [2]:
# The above code can be analysed using lists only without the need of an Array
w1,w2,w3=.2,0.3,0.5
weights =[w1,w2,w3] # Converting them to list Format 

# converting all the regional data to list format to handle it as needed 

kanto=[73,67,43]
johto=[91,88,64]
Hoenn=[87,134,58]
Sinnoh=[102,43,37]
Unova=[69,96,70]

# Converting all the Data to List Format to better Handle it 
# List wihtin lists
region=[kanto,johto,Hoenn,Sinnoh,Unova]


Now Defining a function which will help us to calculate the yeild in tones per hectare using the formula
yeilds_apples = w1*temp + w2*rainfall+ w3*humidity

In [3]:
weights

[0.2, 0.3, 0.5]

In [4]:
kanto

[73, 67, 43]

In [35]:
# We have to return weighted sum 
def calSum(weights,place):
	sum=0
	for i in range(0,3):
		sum+=weights[i]*kanto[i]

	return float(sum)

 ## Now using the function to get the yeild 

In [36]:
# To remove yeild in kanto
calSum(weights,kanto)

56.2

### Revise Loops in Python properly to get use with iteration
### Now the same thing can be acheived by making vector dot product 

Importing the Numpy Module 

In [13]:
import numpy as np 

# Numpy arrays store elements having the same data type 

If you've taken a linear algebra class in high school, you may recognize the above 2-d array as a matrix with five rows and three columns. Each row represents one region, and the columns represent temperature, rainfall, and humidity, respectively.

Numpy arrays can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of an array.

<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="420">


# Single Dimensional Numpy Arrays

Note that the Numpy arrays are similar to those of lists in python except they are multiple times 
faster as compared to that of lists as the inner functions in numpy are written in c++ . Above np is used as an object of numpy

In order to determine what a function does we can simply use the help() method to determine its usecase

In [14]:
# Converting the lists to Numpy Arrays 
arr1 =np.array([1,2,3])
arr2= np.array([4,5,6])
# Created 2 Numpy Arrays 

print(type(arr1))


<class 'numpy.ndarray'>


In [19]:
# Using Numpy Functions 
print(arr1.dot(arr2).sum())
# Sum of all the elements in the array returned after implemeting 
# arr1.dot(arr2) --> return type is an Array and sum() --> Caculates the sum of all the elements

32


In [20]:
Kanto_data1=np.array(kanto) # Converting the lists to Array
weights_arr =np.array(weights) 

In [21]:
print(Kanto_data1.dot(weights_arr))

56.2


In [23]:
arr1



array([1, 2, 3])

# Multidimensional Numpy Arrays

In [32]:
# Two Dimensioanl Arrays 
climate_data =np.array([kanto,
					   Hoenn,
					   johto,
					   Sinnoh,
					   Unova])
# Note that all the above city names already represent lists with data such as temp,rainfall,humidity
# Syntax -->
#  array_name= np.array([Lists_of_Lists])

In [33]:
climate_data

array([[ 73,  67,  43],
       [ 87, 134,  58],
       [ 91,  88,  64],
       [102,  43,  37],
       [ 69,  96,  70]])

### Using Numpy we can have N-Dimensional array we have to just keep Nesting it 

shape --> Attribute helps in defining the dimensions of a given array
Output of Shape --> Tuple () 

In [40]:
print(climate_data)
climate_data.shape
# Denotes 5 rows and 3 columns

[[ 73  67  43]
 [ 87 134  58]
 [ 91  88  64]
 [102  43  37]
 [ 69  96  70]]


(5, 3)

In [41]:
arr1.shape
# One Dimensional Array

(3,)

# Inorder to work with numpy arrays we need all the elements having the same data type 
### .dtype can be used to show data type of an element stored in an array  

In [42]:
climate_data.dtype

dtype('int64')

In [47]:
#  If any one of the Follwing in float all will be converted to floating point 
name_data=np.array(["Sian","Ryan","Smayan","Gadge",234.4])
print(name_data)
name_data.dtype

['Sian' 'Ryan' 'Smayan' 'Gadge' '234.4']


dtype('<U32')

In the above code even though 234.4 was inputted as an integer it has been converted to String dtype 
as all the numpy arrays have same data types

Yeild data for all the locations can be easily computed using the matrix multiplication weights vectors
and climate_data

In [48]:
#  We will receive a return data 
print(np.matmul(climate_data,weights_arr))

[56.2 86.6 76.6 51.8 77.6]


Another method to do Matrix Multiplication is to use the '@' character denoting the matrix multiplication in Numpy