In [2]:
import numpy as py 

## Airhtmetic Operations in Numpy

In [3]:
# Declaring Two Arrays 
arr1= py.array([[1,2,3,4],
			   [5,6,7,8],
			   [9,10,11,12]])

arr2 =py.array([[234,43,53,32],
			   [1,23,43,54],
			   [4,34,5,3]])

In [4]:
print(arr1.shape)
print(arr2.shape)

(3, 4)
(3, 4)


In [5]:
# Both arrays are dimensions wise compatible to be added
print(arr1+arr2)
print(arr1-arr2)
print(arr1/2)#Dividing an array by Scalar 

[[235  45  56  36]
 [  6  29  50  62]
 [ 13  44  16  15]]
[[-233  -41  -50  -28]
 [   4  -17  -36  -46]
 [   5  -24    6    9]]
[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]]


### Array Broadcasting

Numpy arrays also support *broadcasting*, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes. Let's look at an example to see how it works.

When the expression `arr2 + arr4` is evaluated, `arr4` (which has the shape `(4,)`) is replicated three times to match the shape `(3, 4)` of `arr2`. Numpy performs the replication without actually creating three copies of the smaller dimension array, thus improving performance and using lower memory.

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width="360">

## Broadcasting only works if one of the arrays can be replicated to match the other array's shape.

In [6]:
arr_3=py.array([[1,2,3,12]])
arr_4=py.array([[1,2,3,4],
			   [5,6,7,8],
			   [9,10,11,12]])
# Notice here that Both the arrays are of different dimensions but arr_3 can be replicated internally
# by Numpy to match the dimension of arra_4 additional 2 arrays of arr_3 are needed
# 
# But is arr_3=py.array([1,2,3]) --> Broadcasting Not Possible as it cannot be replicated in any form 
# to match the demensioins of arr_4 
print(arr_3+arr_4)

[[ 2  4  6 16]
 [ 6  8 10 20]
 [10 12 14 24]]


## Comparison Operators on Arrays in Numpy	

All the comparison operators can be used on array and the status is returned in terms of boolean array where match condition of the opereators will result in true and others will result in false ``

In [7]:
# sum() --> Which evaluates the sum of array can be used to return number of true cases for given operator
print((arr1==arr2)) #--> Returns arrays of type boolean

print(type(arr1>arr2))

[[False False False False]
 [False False False False]
 [False False False False]]
<class 'numpy.ndarray'>


In [8]:
num1=py.array([[1,2,3],
			   [4,5,6]])
num2 = py.array([[1,2,34],
				 [23,5,45]])

print((num1==num2).sum())

3


In [9]:
num1>num2

array([[False, False, False],
       [False, False, False]])

In [10]:
num2>=num1
print(type(num2>=num1))

<class 'numpy.ndarray'>


## Array indexing & Slicing 

Data Retrievel and Slicing of the array in numpy 